spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 8083
  shutdown: graceful

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx